config/routes.rb
Rails.application.routes.draw do
 

  #get 'sessions/new'

  #get 'sessions/index'
  
  resources :sessions do
    collection do
      get 'statistics'
    end
  end

  get 'static_pages/home'
   devise_scope :user do 
    root to: 'static_pages#home'
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end
  root to: 'static_pages#home'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, controller: 'users/users' do
    member do
      get 'sessions'
    end
  end
  resources :courses

  resources :charges, only: [:new, :create, :index]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def new
    @chosen_recipient = User.find_by(id: params[:to].to_i) if params[:to]
  end

  def create
    recipients = User.where(id: params['recipients'])
    conversation = current_user.send_message(recipients, params[:message][:body], params[:message][:subject]).conversation
    flash[:success] = "Message has been sent"
    redirect_to conversation_path(conversation)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
def recipients_options(chosen_recipient = nil)
		s = ''
		User.all.each do |user|
			s << "<option value='#{user.id}' #{'selected' if user == chosen_recipient}>#{user.name}</option>"
		end
		s.html_safe
	end
end

app/views/messages/new.html.erb
<div class="ui raised segment articles" style="margin: 60px 100px; background: rgb(246, 227, 186);">

  <h4 class="ui dividing large header"><%= t :new_conversation %></h4>
<%= form_tag messages_path, method: :post, class: "ui form"  do %>
<div class="required field">
	<%= label_tag 'message[subject]', t(:subject) %>
	<%= text_field_tag 'message[subject]', nil, required: true %>
</div>

<div class="required field">
	<%= label_tag 'message[body]', t(:message) %>
	<%= text_area_tag 'message[body]', nil, required: true %>
</div>

<div class="field">
	<%= label_tag 'recipients', t(:chose_recipients) %>
	<%= select_tag 'recipients', recipients_options(@chosen_recipient), multiple: true, class: "chosen-it" %>
</div>

<%= submit_tag "Send", class: "ui submit button" %>
<% end %>

</div>