config/routes.rb
Rails.application.routes.draw do
 

  #get 'sessions/new'

  #get 'sessions/index'
  
  resources :sessions do
    collection do
      get 'statistics'
    end
  end

  get 'static_pages/home'
   devise_scope :user do 
    root to: 'static_pages#home'
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end
  root to: 'static_pages#home'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, controller: 'users/users' do
    member do
      get 'sessions'
    end
  end
  resources :courses

  resources :charges, only: [:new, :create, :index]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user! 
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]

  def index
    @conversations = @mailbox.conversations.paginate(page: params[:page], per_page: 10)
    if @box.eql? 'inbox'
      @conversations = @mailbox.inbox
    elsif @box.eql? 'sent'
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end
    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = "The conversation was moved to trash"
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read'
    redirect_to conversations_path
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = "Message sent!"
    redirect_to conversation_path(@conversation)
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = "The conversation was restored"
    redirect_to conversations_path
  end

  private

    def get_mailbox
      @mailbox ||= current_user.mailbox
    end

    def get_conversation
      @conversation ||= @mailbox.conversations.find(params[:id])
    end

    def get_box
      if params[:box].blank? or !["inbox", "sent", "trash"].include?(params[:box])
        params[:box] = 'inbox'
      end
      @box = params[:box]
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, 'item')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.erb
<li class="ui segment">
  <%= link_to conversation.subject, conversation_path(conversation) %>


  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
      <%= link_to t(:restore), restore_conversation_path(conversation), class: "ui mini primary button", method: :post %>
    <% else %>
      <%= link_to t(:move_to_trash), conversation_path(conversation), class: "ui mini negative button", method: :delete %>
      <% if conversation.is_unread?(current_user) %>
        <%= link_to t(:mark_as_read), mark_as_read_conversation_path(conversation),
                    class: 'ui mini primary button', method: :post %>
      <% end %>
    <% end %>
  </div>

<p><%= render 'conversations/participants', conversation: conversation %></p>

  <p><%= truncate conversation.last_message.body, length: 170 %><br>
    <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small></p>

</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
	<% unless participant == current_user %>
	<div class="ui circular tiny image">
		<%= gravatar_for participant %>
	</div>
	<% end %>
<% end %>

app/views/conversations/index.html.erb
<div style="margin-top:-60px;"></div>
<div class="ui grid">
<div class="four wide column">

<div class="ui  segment" style="height:100%;">

<div class="change effect">

<div class="ui small circular image" id="center">
      <div class="ui dimmer">
        <div class="content">
          <div class="center">
            <a href="http://gravatar.com/emails" target=_blank> <div class="ui inverted header" ><u>Change</u></div></a>
          </div>
        </div>
      </div>
      
      <%= gravatar_for(current_user)%>
      
    </div>

<div style="margin: 40px 15px;">
<% if current_user.admin? %>
  
<%= link_to "New Course", new_course_path, class: 'ui fluid teal button', style: "margin-bottom: 10px" %>

<%= link_to "New session", new_session_path, class: 'ui fluid teal button', style: "margin-bottom: 10px" %>
<% end %>
<%= link_to "All Courses", courses_path, class: 'ui fluid blue button', style: "margin-bottom: 10px" %>
<%= link_to "Available sessions", sessions_path, class: 'ui fluid blue button', style: "margin-bottom: 10px" %>

<%= link_to "My sessions", "/users/#{current_user.id}/sessions", class: 'ui fluid blue button', style: "margin-bottom: 10px" %>
<% if current_user.admin? %>
<%= link_to "Statics", statistics_sessions_path, class: 'ui fluid pink button' %>
<% end %>
</div>
<div class="ui large  vertical menu" style="width: 100%;">


<%= mailbox_section "inbox", @box %>
<%= mailbox_section "sent", @box %>
<%= mailbox_section "trash", @box %>

  
</div>


</div>

</div>
</div>
<div class="twelve wide column">
<div class="user-content">
</div>
	
<h1><%= t :conversations %></h1>
<p>
	<%= link_to t(:new_conversation), new_message_path, class: "ui blue button" %>
</p>

	<% if @box == 'trash' %>
		<p>
			<%= link_to t(:empty_trash), empty_trash_conversations_path, class: "ui positive button", method: :delete, data: { confirm: 'Are you sure ?' } %>
		</p>
	<% end %>
	
<ul class="ui items">

	<%= render partial: 'conversations/conversation', collection: @conversations %>
	
</ul>

<%= will_paginate %>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
	<br>
</div>
</div>

app/views/conversations/show.html.erb
<div class="ui raised segment articles" style="margin: 60px 100px; background: rgb(246, 227, 186);">

  <h4 class="ui dividing large header"><%= t :conversation %></h4>
  <div class="ui segment">
<p>
	<%= t :chatting_with %>
	<%= render 'conversations/participants', conversation: @conversation %>
</p>
  	<h4><%= @conversation.subject %></h4>
  	
  	<% @conversation.receipts_for(current_user).each do |receipt| %>

  	<% message = receipt.message %>

	  	<div class="ui comments">
	  		<div class="ui feed">
	  			<div class="event">
				    
				    	<div class="ui tiny circular image" style="width: 10%; margin-right: 10px;">
				    		<%= gravatar_for message.sender %>
				    	</div>
				      
				   
				    <div class="content">
				      <div class="summary">
				        <a><%= message.sender.name %></a><%= " Says at "%>
				        <div class="date">
				          <%= l message.created_at, format: :long %>
				        </div>
				      </div>
				      <div class="extra text">
				       <%= message.body %>
				      </div>
				    </div>
				  </div>
	  		</div>
	  		
	  	</div>
		<% end %>
	<%= form_tag reply_conversation_path(@conversation), method: :post, class: "ui form" do %>
	<div class="field">
		<%= text_area_tag 'body', nil, placeholder: "Type something ..", required: true %>
	</div>
	<%= submit_tag "Send", class: "ui submit button" %>
	<% end %>
  </div>
</div>