config/routes.rb
Rails.application.routes.draw do
 

  #get 'sessions/new'

  #get 'sessions/index'
  
  resources :sessions do
    collection do
      get 'statistics'
    end
  end

  get 'static_pages/home'
   devise_scope :user do 
    root to: 'static_pages#home'
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end
  root to: 'static_pages#home'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, controller: 'users/users' do
    member do
      get 'sessions'
    end
  end
  resources :courses

  resources :charges, only: [:new, :create, :index]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @session = Session.find(params[:id])
  end

  def create
    @session = Session.find(params[:session_id])
    @amount = @session.price.to_i * 100
    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )
    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd'
    )

    @session.users << current_user

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path

  end

  def index
    redirect_to root_url
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<div id="center">
<div class="center-image"><%= image_tag "thankyou.png" %></div><br/>
          <h2>Thank you for buying our courses!</h2><br/>
          <p>you can begin your session right now, check your dashboard</p>
</div>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
 <%= hidden_field_tag :session_id, @session.id %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
      </article>
<h1>Checkout</h1>
<div class="ui divider"></div>
 <h2 class="ui header"><%= @session.title %><a class="ui olive label">Available</a></h2>
<a class="ui teal tag label">$<%= @session.price %></a>
<br/><br/>
<p style="font-style: normal;" >it's simple just click the link below and provide your card informations!</p>
<br/><br/>
<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @session.price * 100 %> "
          data-locale="auto"></script>
<% end %>