config/routes.rb
Rails.application.routes.draw do
 

  #get 'sessions/new'

  #get 'sessions/index'
  
  resources :sessions do
    collection do
      get 'statistics'
    end
  end

  get 'static_pages/home'
   devise_scope :user do 
    root to: 'static_pages#home'
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end
  root to: 'static_pages#home'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, controller: 'users/users' do
    member do
      get 'sessions'
    end
  end
  resources :courses

  resources :charges, only: [:new, :create, :index]
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]
end

app/views/layouts/_navbar.html.erb
<div class="ui inverted massive top blue secondary pointing fixed menu">
  <div class="ui container">
    
    <%= active_link_to 'Home', root_path, class: "item", active: :exact %>
    <%= active_link_to 'Offers', "#", class: "item", active: :exact %>
    <%= active_link_to 'About us', "#", class: "item", active: :exact %>
    <%= active_link_to 'Contact us', "#", class: "item", active: :exact %>
    
    <div class="right menu">
    <% if !user_signed_in? %>
      <div class="item">
        <%= link_to "Log in", new_user_session_url, class: "ui inverted button" %>
      </div>
      <div class="item">
        <%= link_to "Sign up", new_user_registration_url, class: "ui inverted button" %>
      </div>
    <% else %>
      <%= link_to conversations_path, class: 'item' do %>
        
        <%= content_tag :i, "", class: 'user icon' %>Profile
        <% end %>  
      <div class="item">
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EdY</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="wrapper" >
 
      <% if notice %><div class="ui info message"><%= notice %></div><% end %>   
      <% if alert %><div class="ui negative message"><%= alert %></div><% end %>


      <%= yield %>
    </div>
  </body>
</html>